/*
$(document).ready(function() {

    function heightDetect() {
        $('.page-top').css('min-height', $(window).height());
    };

    heightDetect();
    $(window).resize(function() {
        heightDetect();
    });

});
*/

$(document).on("scroll", function(){
	if
    ($(document).scrollTop() > 50){
	  $(".main-header_wrap").addClass("shrink");
	}
	else
	{
		$(".main-header_wrap").removeClass("shrink");
	}
});

jQuery(function($){
   $("#phone").mask("+38 (999) 999-99-99");
});

$('select').selectize({
	create: true,
	sortField: [
	      {
	          field: 'name',
	          direction: 'asc'
	      },
	      {
	          field: '$score'
	      }
	  ],
  options: [
      {value: "Dodge Avenger", name: "Dodge Avenger" },
      {value: "Dodge Caliber", name: "Dodge Caliber" },
      {value: "Dodge Caravan", name: "Dodge Caravan" },
      {value: "Dodge Challenger", name: "Dodge Challenger" },
      {value: "Dodge Charger", name: "Dodge Charger" },
      {value: "Dodge Durango", name: "Dodge Durango" },
      {value: "Dodge Grand Caravan", name: "Dodge Grand Caravan" },
      {value: "Dodge Journey", name: "Dodge Journey" },
      {value: "Dodge Neon", name: "Dodge Neon" },
      {value: "Dodge Nitro", name: "Dodge Nitro" },
      {value: "Dodge Ram 1500", name: "Dodge Ram 1500" },
      {value: "Dodge Ram Van", name: "Dodge Ram Van" },
      {value: "Dodge Stretch Limo", name: "Dodge Stretch Limo" },
      {value: "Land Rover Defender", name: "Land Rover Defender" },
      {value: "Land Rover Discovery", name: "Land Rover Discovery" },
      {value: "Land Rover Freelander", name: "Land Rover Freelander" },
      {value: "Land Rover LR2", name: "Land Rover LR2" },
      {value: "Land Rover LR3", name: "Land Rover LR3" },
      {value: "Land Rover LR4", name: "Land Rover LR4" },
      {value: "Land Rover Range Rover", name: "Land Rover Range Rover" },
      {value: "Land Rover Range Rover Evoque", name: "Land Rover Range Rover Evoque" },
      {value: "Land Rover Range Rover Sport", name: "Land Rover Range Rover Sport" },
      {value: "Chevrolet Aveo", name: "Chevrolet Aveo" },
      {value: "Chevrolet Blazer", name: "Chevrolet Blazer" },
      {value: "Chevrolet Bolt", name: "Chevrolet Bolt" },
      {value: "Chevrolet Captiva", name: "Chevrolet Captiva" },
      {value: "Chevrolet Cobalt", name: "Chevrolet Cobalt" },
      {value: "Chevrolet Cruze", name: "Chevrolet Cruze" },
      {value: "Chevrolet Epica", name: "Chevrolet Epica" },
      {value: "Chevrolet Evanda", name: "Chevrolet Evanda" },
      {value: "Chevrolet HHR", name: "Chevrolet HHR" },
      {value: "Chevrolet Kalos", name: "Chevrolet Kalos" },
      {value: "Chevrolet Lacetti", name: "Chevrolet Lacetti" },
      {value: "Chevrolet Lanos", name: "Chevrolet Lanos" },
      {value: "Chevrolet Malibu", name: "Chevrolet Malibu" },
      {value: "Chevrolet Meriva", name: "Chevrolet Meriva" },
      {value: "Chevrolet Niva", name: "Chevrolet Niva" },
      {value: "Chevrolet Nubira", name: "Chevrolet Nubira" },
      {value: "Chevrolet Orlando", name: "Chevrolet Orlando" },
      {value: "Chevrolet Spark", name: "Chevrolet Spark" },
      {value: "Chevrolet Tacuma", name: "Chevrolet Tacuma" },
      {value: "Chevrolet Tahoe", name: "Chevrolet Tahoe" },
      {value: "Chevrolet Tracker", name: "Chevrolet Tracker" },
      {value: "Chevrolet Trailblazer", name: "Chevrolet Trailblazer" },
      {value: "Chevrolet Volt", name: "Chevrolet Volt" },
      {value: "GMC Acadia", name: "GMC Acadia" },
      {value: "GMC Acadia Denali", name: "GMC Acadia Denali" },
      {value: "GMC Canyon", name: "GMC Canyon" },
      {value: "GMC Envoy", name: "GMC Envoy" },
      {value: "GMC Envoy Denali", name: "GMC Envoy Denali" },
      {value: "GMC Jimmy", name: "GMC Jimmy" },
      {value: "GMC MV1", name: "GMC MV1" },
      {value: "GMC Safari", name: "GMC Safari" },
      {value: "GMC Savana 1500", name: "GMC Savana 1500" },
      {value: "GMC Savana 2500", name: "GMC Savana 2500" },
      {value: "GMC Savana 3500", name: "GMC Savana 3500" },
      {value: "GMC Sierra 1500", name: "GMC Sierra 1500" },
      {value: "GMC Sierra 2500", name: "GMC Sierra 2500" },
      {value: "GMC Sierra 3500", name: "GMC Sierra 3500" },
      {value: "GMC Sonoma", name: "GMC Sonoma" },
      {value: "GMC Suburban", name: "GMC Suburban" },
      {value: "GMC Terrain", name: "GMC Terrain" },
      {value: "GMC Yukon", name: "GMC Yukon" },
      {value: "GMC Yukon Denali", name: "GMC Yukon Denali" },
      {value: "GMC Yukon XL", name: "GMC Yukon XL" },
      {value: "GMC Yukon XL Denali", name: "GMC Yukon XL Denali" },
      {value: "Mitsubishi ASX", name: "Mitsubishi ASX" },
      {value: "Mitsubishi Carisma", name: "Mitsubishi Carisma" },
      {value: "Mitsubishi Colt", name: "Mitsubishi Colt" },
      {value: "Mitsubishi Galant", name: "Mitsubishi Galant" },
      {value: "Mitsubishi Grandis", name: "Mitsubishi Grandis" },
      {value: "Mitsubishi L200", name: "Mitsubishi L200" },
      {value: "Mitsubishi Lancer", name: "Mitsubishi Lancer" },
      {value: "Mitsubishi Outlander", name: "Mitsubishi Outlander" },
      {value: "Mitsubishi Pajero", name: "Mitsubishi Pajero" },
      {value: "Mitsubishi Space Star", name: "Mitsubishi Space Star" },
      {value: "Mitsubishi Space Wagon", name: "Mitsubishi Space Wagon" },
      {value: "Honda Accord", name: "Honda Accord" },
      {value: "Honda Accord Crosstour", name: "Honda Accord Crosstour" },
      {value: "Honda CR-V", name: "Honda CR-V" },
      {value: "Honda Civic", name: "Honda Civic" },
      {value: "Honda Crosstour", name: "Honda Crosstour" },
      {value: "Honda FR-V", name: "Honda FR-V" },
      {value: "Honda Fit", name: "Honda Fit" },
      {value: "Honda HR-V", name: "Honda HR-V" },
      {value: "Honda Insight", name: "Honda Insight" },
      {value: "Honda Integra", name: "Honda Integra" },
      {value: "Honda Jazz", name: "Honda Jazz" },
      {value: "Honda Karisma", name: "Honda Karisma" },
      {value: "Honda Legend", name: "Honda Legend" },
      {value: "Honda Mobilio", name: "Honda Mobilio" },
      {value: "Honda Odyssey", name: "Honda Odyssey" },
      {value: "Honda Pilot", name: "Honda Pilot" },
      {value: "Honda Ridgeline", name: "Honda Ridgeline" },
      {value: "Honda Stream", name: "Honda Stream" },
			{value: "Cadillac BLS", name: "Cadillac BLS" },
      {value: "Cadillac CTS", name: "Cadillac CTS" },
      {value: "Cadillac Escalade", name: "Cadillac Escalade" },
      {value: "Cadillac SRX", name: "Cadillac SRX" },
      {value: "Suzuki Alto", name: "Suzuki Alto" },
      {value: "Suzuki Baleno", name: "Suzuki Baleno" },
      {value: "Suzuki Grand Vitara", name: "Suzuki Grand Vitara" },
      {value: "Suzuki Reno", name: "Suzuki Reno" },
      {value: "Suzuki SX4", name: "Suzuki SX4" },
      {value: "Suzuki Swift", name: "Suzuki Swift" },
      {value: "Suzuki Vitara", name: "Suzuki Vitara" },
      {value: "Volvo 850", name: "Volvo 850" },
      {value: "Volvo C30", name: "Volvo C30" },
      {value: "Volvo C70", name: "Volvo C70" },
      {value: "Volvo S40", name: "Volvo S40" },
      {value: "Volvo S60", name: "Volvo S60" },
      {value: "Volvo S70", name: "Volvo S70" },
      {value: "Volvo S80", name: "Volvo S80" },
      {value: "Volvo S90", name: "Volvo S90" },
      {value: "Volvo Stretch Limo", name: "Volvo Stretch Limo" },
      {value: "Volvo V40", name: "Volvo V40" },
      {value: "Volvo V50", name: "Volvo V50" },
      {value: "Volvo V60", name: "Volvo V60" },
      {value: "Volvo V70", name: "Volvo V70" },
      {value: "Volvo V90", name: "Volvo V90" },
      {value: "Volvo XC60", name: "Volvo XC60" },
      {value: "Volvo XC70", name: "Volvo XC70" },
      {value: "Volvo XC90", name: "Volvo XC90" },
      {value: "Jaguar E-Type", name: "Jaguar E-Type" },
      {value: "Jaguar F-PACE", name: "Jaguar F-PACE" },
      {value: "Jaguar F-Type", name: "Jaguar F-Type" },
      {value: "Jaguar Mark 2", name: "Jaguar Mark 2" },
      {value: "Jaguar S-Type", name: "Jaguar S-Type" },
      {value: "Jaguar X-Type", name: "Jaguar X-Type" },
      {value: "Jaguar XE", name: "Jaguar XE" },
      {value: "Jaguar XF", name: "Jaguar XF" },
      {value: "Jaguar XJ", name: "Jaguar XJ" },
      {value: "Jaguar XJR", name: "Jaguar XJR" },
      {value: "Jaguar XK", name: "Jaguar XK" },
      {value: "Ford B-Max", name: "Ford B-Max" },
      {value: "Ford C-Max", name: "Ford C-Max" },
      {value: "Ford C-Max Hybrid", name: "Ford C-Max Hybrid" },
      {value: "Ford EcoSport", name: "Ford EcoSport" },
      {value: "Ford Edge", name: "Ford Edge" },
      {value: "Ford Escape", name: "Ford Escape" },
      {value: "Ford Escort", name: "Ford Escort" },
      {value: "Ford Explorer", name: "Ford Explorer" },
      {value: "Ford Explorer Sport Trac", name: "Ford Explorer Sport Trac" },
      {value: "Ford Fiesta", name: "Ford Fiesta" },
      {value: "Ford Five Hundred", name: "Ford Five Hundred" },
      {value: "Ford Focus", name: "Ford Focus" },
      {value: "Ford Fusion", name: "Ford Fusion" },
      {value: "Ford Galaxy", name: "Ford Galaxy" },
      {value: "Ford Grand C-Max", name: "Ford Grand C-Max" },
      {value: "Ford Kuga", name: "Ford Kuga" },
      {value: "Ford Maverick", name: "Ford Maverick" },
      {value: "Ford Mondeo", name: "Ford Mondeo" },
      {value: "Ford S-Max", name: "Ford S-Max" },
      {value: "Ford Taurus", name: "Ford Taurus" },
      {value: "Ford Tourneo", name: "Ford Tourneo" },
      {value: "Ford Transit Connect", name: "Ford Transit Connect" },
      {value: "Mazda 3", name: "Mazda 3" },
      {value: "Mazda 323", name: "Mazda 323" },
      {value: "Mazda 626", name: "Mazda 626" },
      {value: "Mazda 929", name: "Mazda 929" },
      {value: "Mazda AZ-Offroad", name: "Mazda AZ-Offroad" },
      {value: "Mazda AZ-Wagon", name: "Mazda AZ-Wagon" },
      {value: "Mazda Allegro", name: "Mazda Allegro" },
      {value: "Mazda Astina", name: "Mazda Astina" },
      {value: "Mazda Atenza", name: "Mazda Atenza" },
      {value: "Mazda Axela", name: "Mazda Axela" },
      {value: "Mazda B-Series", name: "Mazda B-Series" },
      {value: "Mazda BT-50", name: "Mazda BT-50" },
      {value: "Mazda Biante", name: "Mazda Biante" },
      {value: "Mazda Bongo", name: "Mazda Bongo" },
      {value: "Mazda CX-3", name: "Mazda CX-3" },
      {value: "Mazda CX-5", name: "Mazda CX-5" },
      {value: "Mazda CX-7", name: "Mazda CX-7" },
      {value: "Mazda CX-9", name: "Mazda CX-9" },
      {value: "Mazda Capella", name: "Mazda Capella" },
      {value: "Mazda Carol", name: "Mazda Carol" },
      {value: "Mazda Demio", name: "Mazda Demio" },
      {value: "Mazda Familia", name: "Mazda Familia" },
      {value: "Mazda Flair", name: "Mazda Flair" },
      {value: "Mazda Lantis", name: "Mazda Lantis" },
      {value: "Mazda MAZDA2", name: "Mazda MAZDA2" },
      {value: "Mazda MAZDA3", name: "Mazda MAZDA3" },
      {value: "Mazda MAZDA5", name: "Mazda MAZDA5" },
      {value: "Mazda MAZDA6", name: "Mazda MAZDA6" },
      {value: "Mazda MAZDA8", name: "Mazda MAZDA8" },
      {value: "Mazda MAZDASPEED3", name: "Mazda MAZDASPEED3" },
      {value: "Mazda MAZDASPEED6", name: "Mazda MAZDASPEED6" },
      {value: "Mazda MPV", name: "Mazda MPV" },
      {value: "Mazda MX-5 Miata", name: "Mazda MX-5 Miata" },
      {value: "Mazda Millenia", name: "Mazda Millenia" },
      {value: "Mazda Premacy", name: "Mazda Premacy" },
      {value: "Mazda Protege", name: "Mazda Protege" },
      {value: "Mazda RX-8", name: "Mazda RX-8" },
      {value: "Mazda SP23", name: "Mazda SP23" },
      {value: "Mazda SP25", name: "Mazda SP25" },
      {value: "Mazda Scrum", name: "Mazda Scrum" },
      {value: "Mazda Spiano", name: "Mazda Spiano" },
      {value: "Mazda Tribute", name: "Mazda Tribute" },
      {value: "Mazda VX-1", name: "Mazda VX-1" },
      {value: "Mazda Verisa", name: "Mazda Verisa" },
      {value: "Mazda Xedos 6", name: "Mazda Xedos 6" },
      {value: "Mazda Xedos 9", name: "Mazda Xedos 9" },
      {value: "Nissan Almera", name: "Nissan Almera" },
      {value: "Nissan Altima", name: "Nissan Altima" },
      {value: "Nissan Juke", name: "Nissan Juke" },
      {value: "Nissan LEAF", name: "Nissan LEAF" },
      {value: "Nissan Maxima", name: "Nissan Maxima" },
      {value: "Nissan Micra", name: "Nissan Micra" },
      {value: "Nissan Murano", name: "Nissan Murano" },
      {value: "Nissan NV200", name: "Nissan NV200" },
      {value: "Nissan Navara", name: "Nissan Navara" },
      {value: "Nissan Note", name: "Nissan Note" },
      {value: "Nissan Pathfinder", name: "Nissan Pathfinder" },
      {value: "Nissan Patrol", name: "Nissan Patrol" },
      {value: "Nissan Primera", name: "Nissan Primera" },
      {value: "Nissan Pulsar", name: "Nissan Pulsar" },
      {value: "Nissan Qashqai", name: "Nissan Qashqai" },
      {value: "Nissan Rogue", name: "Nissan Rogue" },
      {value: "Nissan Sentra", name: "Nissan Sentra" },
      {value: "Nissan Sunny", name: "Nissan Sunny" },
      {value: "Nissan Teana", name: "Nissan Teana" },
      {value: "Nissan Terrano", name: "Nissan Terrano" },
      {value: "Nissan Tiida", name: "Nissan Tiida" },
      {value: "Nissan X-Trail", name: "Nissan X-Trail" },
      {value: "Lincoln Aviator", name: "Lincoln Aviator" },
      {value: "Lincoln Blackwood", name: "Lincoln Blackwood" },
      {value: "Lincoln Continental", name: "Lincoln Continental" },
      {value: "Lincoln LS", name: "Lincoln LS" },
      {value: "Lincoln MKC", name: "Lincoln MKC" },
      {value: "Lincoln MKS", name: "Lincoln MKS" },
      {value: "Lincoln MKT", name: "Lincoln MKT" },
      {value: "Lincoln MKX", name: "Lincoln MKX" },
      {value: "Lincoln MKZ", name: "Lincoln MKZ" },
      {value: "Lincoln Mark", name: "Lincoln Mark" },
      {value: "Lincoln Mark LT", name: "Lincoln Mark LT" },
      {value: "Lincoln Navigator", name: "Lincoln Navigator" },
      {value: "Lincoln Stretch Limo", name: "Lincoln Stretch Limo" },
      {value: "Lincoln Town Car", name: "Lincoln Town Car" },
      {value: "Lincoln Zephyr", name: "Lincoln Zephyr" },
      {value: "Toyota Auris", name: "Toyota Auris" },
      {value: "Toyota Auris Touring Sports", name: "Toyota Auris Touring Sports" },
      {value: "Toyota Avalon", name: "Toyota Avalon" },
      {value: "Toyota Avensis", name: "Toyota Avensis" },
      {value: "Toyota Aygo", name: "Toyota Aygo" },
      {value: "Toyota Camry", name: "Toyota Camry" },
      {value: "Toyota Corolla", name: "Toyota Corolla" },
      {value: "Toyota Highlander", name: "Toyota Highlander" },
      {value: "Toyota Hilux", name: "Toyota Hilux" },
      {value: "Toyota Land Cruiser", name: "Toyota Land Cruiser" },
      {value: "Toyota Matrix", name: "Toyota Matrix" },
      {value: "Toyota Prado", name: "Toyota Prado" },
      {value: "Toyota Prius", name: "Toyota Prius" },
      {value: "Toyota RAV4", name: "Toyota RAV4" },
      {value: "Toyota Stretch Limo", name: "Toyota Stretch Limo" },
      {value: "Toyota Tacoma", name: "Toyota Tacoma" },
      {value: "Toyota Venza", name: "Toyota Venza" },
      {value: "Toyota Verso", name: "Toyota Verso" },
      {value: "Toyota Yaris", name: "Toyota Yaris" },
      {value: "Saab 42980", name: "Saab 42980" },
      {value: "Saab 9-2X", name: "Saab 9-2X" },
      {value: "Saab 42981", name: "Saab 42981" },
      {value: "Saab 9-3X", name: "Saab 9-3X" },
      {value: "Saab 9-4X", name: "Saab 9-4X" },
      {value: "Saab 42983", name: "Saab 42983" },
      {value: "Saab 9-7X", name: "Saab 9-7X" },
      {value: "Saab Sport", name: "Saab Sport" },
      {value: "Saab Vector", name: "Saab Vector" },
      {value: "Volkswagen Amarok", name: "Volkswagen Amarok" },
      {value: "Volkswagen Beetle", name: "Volkswagen Beetle" },
      {value: "Volkswagen Bora", name: "Volkswagen Bora" },
      {value: "Volkswagen CC", name: "Volkswagen CC" },
      {value: "Volkswagen Caddy", name: "Volkswagen Caddy" },
      {value: "Volkswagen Caravelle", name: "Volkswagen Caravelle" },
      {value: "Volkswagen Golf", name: "Volkswagen Golf" },
      {value: "Volkswagen Golf Variant", name: "Volkswagen Golf Variant" },
      {value: "Volkswagen Jetta", name: "Volkswagen Jetta" },
      {value: "Volkswagen Multivan", name: "Volkswagen Multivan" },
      {value: "Volkswagen Passat", name: "Volkswagen Passat" },
      {value: "Volkswagen Phaeton", name: "Volkswagen Phaeton" },
      {value: "Volkswagen Polo", name: "Volkswagen Polo" },
      {value: "Volkswagen Polo Sedan", name: "Volkswagen Polo Sedan" },
      {value: "Volkswagen Sharan", name: "Volkswagen Sharan" },
      {value: "Volkswagen Tiguan", name: "Volkswagen Tiguan" },
      {value: "Volkswagen Touareg", name: "Volkswagen Touareg" },
      {value: "Volkswagen Touran", name: "Volkswagen Touran" },
      {value: "Volkswagen Transporter", name: "Volkswagen Transporter" },
      {value: "Volkswagen e-up!", name: "Volkswagen e-up!" },
      {value: "Acura CL", name: "Acura CL" },
      {value: "Acura MDX", name: "Acura MDX" },
      {value: "Acura RDX", name: "Acura RDX" },
      {value: "Acura TL", name: "Acura TL" },
      {value: "Acura TSX", name: "Acura TSX" },
      {value: "Pontiac Vibe", name: "Pontiac Vibe" },
      {value: "Hyundai Accent", name: "Hyundai Accent" },
      {value: "Hyundai Elantra", name: "Hyundai Elantra" },
      {value: "Hyundai Equus", name: "Hyundai Equus" },
      {value: "Hyundai Genesis", name: "Hyundai Genesis" },
      {value: "Hyundai Getz", name: "Hyundai Getz" },
      {value: "Hyundai Grand Santa Fe", name: "Hyundai Grand Santa Fe" },
      {value: "Hyundai Grandeur", name: "Hyundai Grandeur" },
      {value: "Hyundai H-1", name: "Hyundai H-1" },
      {value: "Hyundai Matrix", name: "Hyundai Matrix" },
      {value: "Hyundai Santa Fe", name: "Hyundai Santa Fe" },
      {value: "Hyundai Solaris", name: "Hyundai Solaris" },
      {value: "Hyundai Sonata", name: "Hyundai Sonata" },
      {value: "Hyundai Starex", name: "Hyundai Starex" },
      {value: "Hyundai Terracan", name: "Hyundai Terracan" },
      {value: "Hyundai Trajet", name: "Hyundai Trajet" },
      {value: "Hyundai Tucson", name: "Hyundai Tucson" },
      {value: "Hyundai Veracruz", name: "Hyundai Veracruz" },
      {value: "Hyundai i10", name: "Hyundai i10" },
      {value: "Hyundai i20", name: "Hyundai i20" },
      {value: "Hyundai i30", name: "Hyundai i30" },
      {value: "Hyundai i35", name: "Hyundai i35" },
      {value: "Hyundai i40", name: "Hyundai i40" },
      {value: "Hyundai ix20", name: "Hyundai ix20" },
      {value: "Hyundai ix25", name: "Hyundai ix25" },
      {value: "Hyundai ix35", name: "Hyundai ix35" },
      {value: "Hyundai ix55", name: "Hyundai ix55" },
      {value: "Kia Carens", name: "Kia Carens" },
      {value: "Kia Carnival", name: "Kia Carnival" },
      {value: "Kia Cee'd", name: "Kia Cee'd" },
      {value: "Kia Cee'd Sportswagon", name: "Kia Cee'd Sportswagon" },
      {value: "Kia Cerato", name: "Kia Cerato" },
      {value: "Kia Magentis", name: "Kia Magentis" },
      {value: "Kia Mohave", name: "Kia Mohave" },
      {value: "Kia Opirus", name: "Kia Opirus" },
      {value: "Kia Optima", name: "Kia Optima" },
      {value: "Kia Picanto", name: "Kia Picanto" },
      {value: "Kia Quoris", name: "Kia Quoris" },
      {value: "Kia Rio", name: "Kia Rio" },
      {value: "Kia Sorento", name: "Kia Sorento" },
      {value: "Kia Soul", name: "Kia Soul" },
      {value: "Kia Sportage", name: "Kia Sportage" },
      {value: "Kia Stylus", name: "Kia Stylus" },
      {value: "Kia Venga", name: "Kia Venga" },
      {value: "Subaru B9 Tribeca", name: "Subaru B9 Tribeca" },
      {value: "Subaru Forester", name: "Subaru Forester" },
      {value: "Subaru Impreza", name: "Subaru Impreza" },
      {value: "Subaru Legacy", name: "Subaru Legacy" },
      {value: "Subaru Outback", name: "Subaru Outback" },
      {value: "Subaru Tribeca", name: "Subaru Tribeca" },
      {value: "Subaru XV Crosstrek", name: "Subaru XV Crosstrek" },
      {value: "Infiniti EX", name: "Infiniti EX" },
      {value: "Infiniti FX", name: "Infiniti FX" },
      {value: "Infiniti G Sedan", name: "Infiniti G Sedan" },
      {value: "Infiniti M", name: "Infiniti M" },
      {value: "Infiniti Q50", name: "Infiniti Q50" },
      {value: "Infiniti QX56", name: "Infiniti QX56" },
      {value: "Mercedes-Benz 190", name: "Mercedes-Benz 190" },
      {value: "Mercedes-Benz 220", name: "Mercedes-Benz 220" },
      {value: "Mercedes-Benz A-Class", name: "Mercedes-Benz A-Class" },
      {value: "Mercedes-Benz AMG GT", name: "Mercedes-Benz AMG GT" },
      {value: "Mercedes-Benz B-Class", name: "Mercedes-Benz B-Class" },
      {value: "Mercedes-Benz B200", name: "Mercedes-Benz B200" },
      {value: "Mercedes-Benz C-Class", name: "Mercedes-Benz C-Class" },
      {value: "Mercedes-Benz CL-Class", name: "Mercedes-Benz CL-Class" },
      {value: "Mercedes-Benz CLA-Class", name: "Mercedes-Benz CLA-Class" },
      {value: "Mercedes-Benz CLK-Class", name: "Mercedes-Benz CLK-Class" },
      {value: "Mercedes-Benz CLS-Class", name: "Mercedes-Benz CLS-Class" },
      {value: "Mercedes-Benz Citan", name: "Mercedes-Benz Citan" },
      {value: "Mercedes-Benz E-Class", name: "Mercedes-Benz E-Class" },
      {value: "Mercedes-Benz E-Class Wagon", name: "Mercedes-Benz E-Class Wagon" },
      {value: "Mercedes-Benz G-Class", name: "Mercedes-Benz G-Class" },
      {value: "Mercedes-Benz GL-Class", name: "Mercedes-Benz GL-Class" },
      {value: "Mercedes-Benz GLA-Class", name: "Mercedes-Benz GLA-Class" },
      {value: "Mercedes-Benz GLC-Class", name: "Mercedes-Benz GLC-Class" },
      {value: "Mercedes-Benz GLE-Class", name: "Mercedes-Benz GLE-Class" },
      {value: "Mercedes-Benz GLK-Class", name: "Mercedes-Benz GLK-Class" },
      {value: "Mercedes-Benz GLS-Class", name: "Mercedes-Benz GLS-Class" },
      {value: "Mercedes-Benz M-Class", name: "Mercedes-Benz M-Class" },
      {value: "Mercedes-Benz ML Class", name: "Mercedes-Benz ML Class" },
      {value: "Mercedes-Benz Metris", name: "Mercedes-Benz Metris" },
      {value: "Mercedes-Benz R-Class", name: "Mercedes-Benz R-Class" },
      {value: "Mercedes-Benz S-Class", name: "Mercedes-Benz S-Class" },
      {value: "Mercedes-Benz SL-Class", name: "Mercedes-Benz SL-Class" },
      {value: "Mercedes-Benz SLK-Class", name: "Mercedes-Benz SLK-Class" },
      {value: "Mercedes-Benz SLR McLaren", name: "Mercedes-Benz SLR McLaren" },
      {value: "Mercedes-Benz SLS AMG", name: "Mercedes-Benz SLS AMG" },
      {value: "Mercedes-Benz Sprinter", name: "Mercedes-Benz Sprinter" },
      {value: "Mercedes-Benz Stretch Limo", name: "Mercedes-Benz Stretch Limo" },
      {value: "Mercedes-Benz V-Class", name: "Mercedes-Benz V-Class" },
      {value: "Mercedes-Benz Valente", name: "Mercedes-Benz Valente" },
      {value: "Mercedes-Benz Vaneo", name: "Mercedes-Benz Vaneo" },
      {value: "Mercedes-Benz Viano", name: "Mercedes-Benz Viano" },
      {value: "Mercedes-Benz Vito", name: "Mercedes-Benz Vito" },
      {value: "Jeep 2500", name: "Jeep 2500" },
      {value: "Jeep Cherokee", name: "Jeep Cherokee" },
      {value: "Jeep Commander", name: "Jeep Commander" },
      {value: "Jeep Compass", name: "Jeep Compass" },
      {value: "Jeep Grand Cherokee", name: "Jeep Grand Cherokee" },
      {value: "Jeep Liberty", name: "Jeep Liberty" },
      {value: "Jeep Patriot", name: "Jeep Patriot" },
      {value: "Jeep Renegade", name: "Jeep Renegade" },
      {value: "Jeep Wrangler", name: "Jeep Wrangler" },
      {value: "Chrysler 300", name: "Chrysler 300" },
      {value: "Chrysler Grand Voyager", name: "Chrysler Grand Voyager" },
      {value: "Chrysler PT Cruiser", name: "Chrysler PT Cruiser" },
      {value: "Chrysler Pacifica", name: "Chrysler Pacifica" },
      {value: "Chrysler Sebring", name: "Chrysler Sebring" },
      {value: "Chrysler Voyager", name: "Chrysler Voyager" },
      {value: "Lexus CT", name: "Lexus CT" },
      {value: "Lexus ES", name: "Lexus ES" },
      {value: "Lexus GS", name: "Lexus GS" },
      {value: "Lexus GX", name: "Lexus GX" },
      {value: "Lexus HS", name: "Lexus HS" },
      {value: "Lexus IS", name: "Lexus IS" },
      {value: "Lexus LFA", name: "Lexus LFA" },
      {value: "Lexus LS", name: "Lexus LS" },
      {value: "Lexus LX", name: "Lexus LX" },
      {value: "Lexus NX", name: "Lexus NX" },
      {value: "Lexus RC", name: "Lexus RC" },
      {value: "Lexus RX", name: "Lexus RX" },
      {value: "Lexus SC", name: "Lexus SC" },
      {value: "BMW 1-series", name: "BMW 1-series" },
      {value: "BMW 2-series", name: "BMW 2-series" },
      {value: "BMW 3-series", name: "BMW 3-series" },
      {value: "BMW 4-series", name: "BMW 4-series" },
      {value: "BMW 5-series", name: "BMW 5-series" },
      {value: "BMW 6-series", name: "BMW 6-series" },
      {value: "BMW 7-series", name: "BMW 7-series" },
      {value: "BMW X1", name: "BMW X1" },
      {value: "BMW X3", name: "BMW X3" },
      {value: "BMW X4", name: "BMW X4" },
      {value: "BMW X5", name: "BMW X5" },
      {value: "BMW X6", name: "BMW X6" },
      {value: "Porsche 718", name: "Porsche 718" },
      {value: "Porsche 911", name: "Porsche 911" },
      {value: "Porsche 912", name: "Porsche 912" },
      {value: "Porsche 918", name: "Porsche 918" },
      {value: "Porsche Boxster", name: "Porsche Boxster" },
      {value: "Porsche Cayenne", name: "Porsche Cayenne" },
      {value: "Porsche Cayman", name: "Porsche Cayman" },
      {value: "Porsche Macan", name: "Porsche Macan" },
      {value: "Porsche Macan Turbo", name: "Porsche Macan Turbo" },
      {value: "Porsche Panamera", name: "Porsche Panamera" },
      {value: "Porsche Targa", name: "Porsche Targa" },
      {value: "Daewoo Espero", name: "Daewoo Espero" },
      {value: "Daewoo Gentra", name: "Daewoo Gentra" },
      {value: "Daewoo Kalos", name: "Daewoo Kalos" },
      {value: "Daewoo Lanos", name: "Daewoo Lanos" },
      {value: "Daewoo Leganza", name: "Daewoo Leganza" },
      {value: "Daewoo Nexia", name: "Daewoo Nexia" },
      {value: "Daewoo Nubira", name: "Daewoo Nubira" },
      {value: "Daewoo Tacuma", name: "Daewoo Tacuma" },
      {value: "Audi A1", name: "Audi A1" },
      {value: "Audi A2", name: "Audi A2" },
      {value: "Audi A3", name: "Audi A3" },
      {value: "Audi A4", name: "Audi A4" },
      {value: "Audi A5", name: "Audi A5" },
      {value: "Audi A6", name: "Audi A6" },
      {value: "Audi A6 Avant", name: "Audi A6 Avant" },
      {value: "Audi A7", name: "Audi A7" },
      {value: "Audi A8", name: "Audi A8" },
      {value: "Audi Q3", name: "Audi Q3" },
      {value: "Audi Q5", name: "Audi Q5" },
      {value: "Audi Q7", name: "Audi Q7" },
      {value: "Audi S5", name: "Audi S5" },
      {value: "Hummer H1", name: "Hummer H1" },
      {value: "Hummer H2", name: "Hummer H2" },
      {value: "Hummer H2 SUT", name: "Hummer H2 SUT" },
      {value: "Hummer H3", name: "Hummer H3" },
      {value: "Hummer H3T", name: "Hummer H3T" },
      {value: "Hummer MV-1", name: "Hummer MV-1" },
      {value: "Hummer Stretch Limo", name: "Hummer Stretch Limo" },
      {value: "Mini Cooper", name: "Mini Cooper" },
      {value: "Mini Countryman", name: "Mini Countryman" },
      {value: "Aston Martin DB9", name: "Aston Martin DB9" },
      {value: "Scion FR-S", name: "Scion FR-S" },
      {value: "Scion iA", name: "Scion iA" },
      {value: "Scion iM", name: "Scion iM" },
      {value: "Scion iQ", name: "Scion iQ" },
      {value: "Scion tC", name: "Scion tC" },
      {value: "Scion xA", name: "Scion xA" },
      {value: "Scion xB", name: "Scion xB" },
      {value: "Scion xD", name: "Scion xD" },
      {value: "Maserati Coupe", name: "Maserati Coupe" },
      {value: "Maserati Ghibli", name: "Maserati Ghibli" },
      {value: "Maserati Gran Turismo", name: "Maserati Gran Turismo" },
      {value: "Maserati GranCabrio", name: "Maserati GranCabrio" },
      {value: "Maserati GranSport", name: "Maserati GranSport" },
      {value: "Maserati Levante", name: "Maserati Levante" },
      {value: "Maserati MC12", name: "Maserati MC12" },
      {value: "Maserati Quattroporte", name: "Maserati Quattroporte" },
      {value: "Maserati Spyder", name: "Maserati Spyder" },
      {value: "Bentley Arnage", name: "Bentley Arnage" },
      {value: "Rolls-Royce Phantom", name: "Rolls-Royce Phantom" },
      {value: "Lamborghini Gallardo", name: "Lamborghini Gallardo" },
      {value: "Smart Forfour", name: "Smart Forfour" },
      {value: "Tesla Model S", name: "Tesla Model S" },
      {value: "Tesla Model X", name: "Tesla Model X" },
      {value: "Fiat 500", name: "Fiat 500" },
      {value: "Fiat 500L", name: "Fiat 500L" },
      {value: "Fiat Albea", name: "Fiat Albea" },
      {value: "Fiat Bravo", name: "Fiat Bravo" },
      {value: "Fiat Croma", name: "Fiat Croma" },
      {value: "Fiat Doblo", name: "Fiat Doblo" },
      {value: "Fiat Ducato", name: "Fiat Ducato" },
      {value: "Fiat Fiorino", name: "Fiat Fiorino" },
      {value: "Fiat Freemont", name: "Fiat Freemont" },
      {value: "Fiat Grande Punto", name: "Fiat Grande Punto" },
      {value: "Fiat Linea", name: "Fiat Linea" },
      {value: "Fiat Multipla", name: "Fiat Multipla" },
      {value: "Fiat Panda", name: "Fiat Panda" },
      {value: "Fiat Punto", name: "Fiat Punto" },
      {value: "Fiat Qubo", name: "Fiat Qubo" },
      {value: "Fiat Scudo", name: "Fiat Scudo" },
      {value: "Fiat Siena", name: "Fiat Siena" },
      {value: "Fiat Tipo", name: "Fiat Tipo" },
      {value: "Citroen Berlingo", name: "Citroen Berlingo" },
      {value: "Citroen C-Crosser", name: "Citroen C-Crosser" },
      {value: "Citroen C-Elysee", name: "Citroen C-Elysee" },
      {value: "Citroen C-Zero", name: "Citroen C-Zero" },
      {value: "Citroen C3", name: "Citroen C3" },
      {value: "Citroen C3 Picasso", name: "Citroen C3 Picasso" },
      {value: "Citroen C4", name: "Citroen C4" },
      {value: "Citroen C4 Cactus", name: "Citroen C4 Cactus" },
      {value: "Citroen C4 Picasso", name: "Citroen C4 Picasso" },
      {value: "Citroen C5", name: "Citroen C5" },
      {value: "Citroen C6", name: "Citroen C6" },
      {value: "Citroen DS3", name: "Citroen DS3" },
      {value: "Citroen DS4", name: "Citroen DS4" },
      {value: "Citroen DS5", name: "Citroen DS5" },
      {value: "Citroen Elysee", name: "Citroen Elysee" },
      {value: "Citroen Jumpy", name: "Citroen Jumpy" },
      {value: "Citroen Nemo", name: "Citroen Nemo" },
      {value: "Citroen Xsara", name: "Citroen Xsara" },
      {value: "Alfa Romeo 147", name: "Alfa Romeo 147" },
      {value: "Alfa Romeo 156", name: "Alfa Romeo 156" },
      {value: "Alfa Romeo 159", name: "Alfa Romeo 159" },
      {value: "Alfa Romeo Giulietta", name: "Alfa Romeo Giulietta" },
      {value: "Alfa Romeo Mito", name: "Alfa Romeo Mito" },
      {value: "Peugeot 1007", name: "Peugeot 1007" },
      {value: "Peugeot 2008", name: "Peugeot 2008" },
      {value: "Peugeot 206", name: "Peugeot 206" },
      {value: "Peugeot 207", name: "Peugeot 207" },
      {value: "Peugeot 208", name: "Peugeot 208" },
      {value: "Peugeot 3008", name: "Peugeot 3008" },
      {value: "Peugeot 301", name: "Peugeot 301" },
      {value: "Peugeot 307", name: "Peugeot 307" },
      {value: "Peugeot 308", name: "Peugeot 308" },
      {value: "Peugeot 308 SW", name: "Peugeot 308 SW" },
      {value: "Peugeot 4007", name: "Peugeot 4007" },
      {value: "Peugeot 406", name: "Peugeot 406" },
      {value: "Peugeot 407", name: "Peugeot 407" },
      {value: "Peugeot 408", name: "Peugeot 408" },
      {value: "Peugeot 5008", name: "Peugeot 5008" },
      {value: "Peugeot 508", name: "Peugeot 508" },
      {value: "Peugeot 607", name: "Peugeot 607" },
      {value: "Peugeot 807", name: "Peugeot 807" },
      {value: "Peugeot Bipper", name: "Peugeot Bipper" },
      {value: "Peugeot Expert", name: "Peugeot Expert" },
      {value: "Peugeot Partner", name: "Peugeot Partner" },
      {value: "Seat Alhambra", name: "Seat Alhambra" },
      {value: "Seat Altea", name: "Seat Altea" },
      {value: "Seat Cordoba", name: "Seat Cordoba" },
      {value: "Seat Exeo", name: "Seat Exeo" },
      {value: "Seat Ibiza", name: "Seat Ibiza" },
      {value: "Seat Leon", name: "Seat Leon" },
      {value: "Seat Toledo", name: "Seat Toledo" },
      {value: "Seat X-Perience", name: "Seat X-Perience" },
      {value: "Renault Captur", name: "Renault Captur" },
      {value: "Renault Clio", name: "Renault Clio" },
      {value: "Renault Clio Break", name: "Renault Clio Break" },
      {value: "Renault Dokker", name: "Renault Dokker" },
      {value: "Renault Duster", name: "Renault Duster" },
      {value: "Renault Duster Oroch", name: "Renault Duster Oroch" },
      {value: "Renault Espace", name: "Renault Espace" },
      {value: "Renault Fluence", name: "Renault Fluence" },
      {value: "Renault Grand Scenic", name: "Renault Grand Scenic" },
      {value: "Renault Kadjar", name: "Renault Kadjar" },
      {value: "Renault Kangoo", name: "Renault Kangoo" },
      {value: "Renault Koleos", name: "Renault Koleos" },
      {value: "Renault Kwid", name: "Renault Kwid" },
      {value: "Renault Laguna", name: "Renault Laguna" },
      {value: "Renault Latitude", name: "Renault Latitude" },
      {value: "Renault Lodgy", name: "Renault Lodgy" },
      {value: "Renault Logan", name: "Renault Logan" },
      {value: "Renault Master", name: "Renault Master" },
      {value: "Renault Megane", name: "Renault Megane" },
      {value: "Renault Megane Estate", name: "Renault Megane Estate" },
      {value: "Renault Modus", name: "Renault Modus" },
      {value: "Renault New Logan", name: "Renault New Logan" },
      {value: "Renault Pulse", name: "Renault Pulse" },
      {value: "Renault Safrane", name: "Renault Safrane" },
      {value: "Renault Sandero", name: "Renault Sandero" },
      {value: "Renault Scala", name: "Renault Scala" },
      {value: "Renault Scenic", name: "Renault Scenic" },
      {value: "Renault Stepway", name: "Renault Stepway" },
      {value: "Renault Symbol", name: "Renault Symbol" },
      {value: "Renault Talisman", name: "Renault Talisman" },
      {value: "Renault Thalia", name: "Renault Thalia" },
      {value: "Renault Tondar", name: "Renault Tondar" },
      {value: "Renault Trafic", name: "Renault Trafic" },
      {value: "Renault Twingo", name: "Renault Twingo" },
      {value: "Renault Vel Satis", name: "Renault Vel Satis" },
      {value: "Renault Zoe", name: "Renault Zoe" },
      {value: "Skoda Fabia", name: "Skoda Fabia" },
      {value: "Skoda Octavia", name: "Skoda Octavia" },
      {value: "Skoda Octavia Combi", name: "Skoda Octavia Combi" },
      {value: "Skoda Rapid", name: "Skoda Rapid" },
      {value: "Skoda Rapid Spaceback", name: "Skoda Rapid Spaceback" },
      {value: "Skoda Roomster", name: "Skoda Roomster" },
      {value: "Skoda Superb", name: "Skoda Superb" },
      {value: "Skoda Superb Combi", name: "Skoda Superb Combi" },
      {value: "Skoda Yeti", name: "Skoda Yeti" },
      {value: "Ssangyong Actyon", name: "Ssangyong Actyon" },
      {value: "Ssangyong Korando", name: "Ssangyong Korando" },
      {value: "Ssangyong Kyron", name: "Ssangyong Kyron" },
      {value: "Ssangyong Rexton", name: "Ssangyong Rexton" },
      {value: "Ssangyong Rodius", name: "Ssangyong Rodius" },
      {value: "Ssangyong Stavic", name: "Ssangyong Stavic" },
      {value: "Dacia Duster", name: "Dacia Duster" },
      {value: "Dacia Lodgy", name: "Dacia Lodgy" },
      {value: "Dacia Logan", name: "Dacia Logan" },
      {value: "Dacia Sandero", name: "Dacia Sandero" },
      {value: "Opel Adam", name: "Opel Adam" },
      {value: "Opel Ampera", name: "Opel Ampera" },
      {value: "Opel Antara", name: "Opel Antara" },
      {value: "Opel Astra", name: "Opel Astra" },
      {value: "Opel Combo C", name: "Opel Combo C" },
      {value: "Opel Combo D", name: "Opel Combo D" },
      {value: "Opel Corsa", name: "Opel Corsa" },
      {value: "Opel Insignia", name: "Opel Insignia" },
      {value: "Opel Meriva", name: "Opel Meriva" },
      {value: "Opel Mokka", name: "Opel Mokka" },
      {value: "Opel Omega", name: "Opel Omega" },
      {value: "Opel Signum", name: "Opel Signum" },
      {value: "Opel Vectra", name: "Opel Vectra" },
      {value: "Opel Vivaro", name: "Opel Vivaro" },
      {value: "Opel Zafira", name: "Opel Zafira" },
      {value: "Daihatsu Materia", name: "Daihatsu Materia" },
      {value: "Daihatsu Sirion", name: "Daihatsu Sirion" },
      {value: "Daihatsu Terios", name: "Daihatsu Terios" },
      {value: "Lancia Delta", name: "Lancia Delta" },
      {value: "Lancia Lybra", name: "Lancia Lybra" },
      {value: "Lancia Phedra", name: "Lancia Phedra" },
      {value: "Lancia Thema", name: "Lancia Thema" },
      {value: "Lancia Thesis", name: "Lancia Thesis" },
      {value: "Lancia Ypsilon", name: "Lancia Ypsilon" },
      {value: "Holden Adventra", name: "Holden Adventra" },
      {value: "Holden Astra", name: "Holden Astra" },
      {value: "Holden Barina", name: "Holden Barina" },
      {value: "Holden Barina Spark", name: "Holden Barina Spark" },
      {value: "Holden Berlina", name: "Holden Berlina" },
      {value: "Holden Calais", name: "Holden Calais" },
      {value: "Holden Caprice", name: "Holden Caprice" },
      {value: "Holden Captiva", name: "Holden Captiva" },
      {value: "Holden Cascada", name: "Holden Cascada" },
      {value: "Holden Clubsport", name: "Holden Clubsport" },
      {value: "Holden Colorado", name: "Holden Colorado" },
      {value: "Holden Colorado 7", name: "Holden Colorado 7" },
      {value: "Holden Commodore", name: "Holden Commodore" },
      {value: "Holden Crewman", name: "Holden Crewman" },
      {value: "Holden Cruze", name: "Holden Cruze" },
      {value: "Holden Epica", name: "Holden Epica" },
      {value: "Holden GTS", name: "Holden GTS" },
      {value: "Holden Grange", name: "Holden Grange" },
      {value: "Holden Insignia", name: "Holden Insignia" },
      {value: "Holden Malibu", name: "Holden Malibu" },
      {value: "Holden Rodeo", name: "Holden Rodeo" },
      {value: "Holden SV6", name: "Holden SV6" },
      {value: "Holden Statesman", name: "Holden Statesman" },
      {value: "Holden Stretch Limo", name: "Holden Stretch Limo" },
      {value: "Holden Tigra", name: "Holden Tigra" },
      {value: "Holden Trax", name: "Holden Trax" },
      {value: "Holden Vectra", name: "Holden Vectra" },
      {value: "Holden Viva", name: "Holden Viva" },
      {value: "Holden Volt", name: "Holden Volt" },
      {value: "Holden Zafira", name: "Holden Zafira" },
      {value: "Rover 45", name: "Rover 45" },
      {value: "Great Wall C30", name: "Great Wall C30" },
      {value: "Great Wall C50", name: "Great Wall C50" },
      {value: "Great Wall Haval H1", name: "Great Wall Haval H1" },
      {value: "Great Wall Haval H2", name: "Great Wall Haval H2" },
      {value: "Great Wall Haval H3", name: "Great Wall Haval H3" },
      {value: "Great Wall Haval H5", name: "Great Wall Haval H5" },
      {value: "Great Wall Haval H6", name: "Great Wall Haval H6" },
      {value: "Great Wall Haval H7", name: "Great Wall Haval H7" },
      {value: "Great Wall Haval H8", name: "Great Wall Haval H8" },
      {value: "Great Wall Haval H9", name: "Great Wall Haval H9" },
      {value: "Great Wall Haval M2", name: "Great Wall Haval M2" },
      {value: "Great Wall Haval M4", name: "Great Wall Haval M4" },
      {value: "Great Wall Hover", name: "Great Wall Hover" },
      {value: "Great Wall Hover 5", name: "Great Wall Hover 5" },
      {value: "Great Wall Voleex", name: "Great Wall Voleex" },
      {value: "Great Wall X200", name: "Great Wall X200" },
      {value: "Lada Granta", name: "Lada Granta" },
      {value: "Lada Kalina", name: "Lada Kalina" },
      {value: "Lada Largus", name: "Lada Largus" },
      {value: "Lada Priora", name: "Lada Priora" },
      {value: "Lada Vesta", name: "Lada Vesta" },
      {value: "Lada Xray", name: "Lada Xray" },
      {value: "Maybach 57", name: "Maybach 57" },
      {value: "Maybach 62", name: "Maybach 62" },
      {value: "Vauxhall Antara", name: "Vauxhall Antara" },
      {value: "Vauxhall Astra", name: "Vauxhall Astra" },
      {value: "Vauxhall Insignia", name: "Vauxhall Insignia" },
      {value: "Vauxhall Meriva", name: "Vauxhall Meriva" },
      {value: "Vauxhall Signum", name: "Vauxhall Signum" },
      {value: "Vauxhall Vectra", name: "Vauxhall Vectra" },
      {value: "Vauxhall Vivaro", name: "Vauxhall Vivaro" },
      {value: "Vauxhall Zafira", name: "Vauxhall Zafira" },
      {value: "BYD F3", name: "BYD F3" },
      {value: "BYD F5 Suri", name: "BYD F5 Suri" },
      {value: "BYD F6", name: "BYD F6" },
      {value: "BYD F7", name: "BYD F7" },
      {value: "BYD G3", name: "BYD G3" },
      {value: "BYD G3R", name: "BYD G3R" },
      {value: "BYD G5", name: "BYD G5" },
      {value: "BYD S6", name: "BYD S6" },
      {value: "Geely 515", name: "Geely 515" },
      {value: "Geely Borui", name: "Geely Borui" },
      {value: "Geely CK", name: "Geely CK" },
      {value: "Geely Dorsett", name: "Geely Dorsett" },
      {value: "Geely EC8", name: "Geely EC8" },
      {value: "Geely EX7", name: "Geely EX7" },
      {value: "Geely Emgrand 7", name: "Geely Emgrand 7" },
      {value: "Geely Emgrand 8", name: "Geely Emgrand 8" },
      {value: "Geely Emgrand EC7", name: "Geely Emgrand EC7" },
      {value: "Geely Emgrand EC718", name: "Geely Emgrand EC718" },
      {value: "Geely Emgrand EC8", name: "Geely Emgrand EC8" },
      {value: "Geely Emgrand X7", name: "Geely Emgrand X7" },
      {value: "Geely GC2", name: "Geely GC2" },
      {value: "Geely GC5", name: "Geely GC5" },
      {value: "Geely GC6", name: "Geely GC6" },
      {value: "Geely GC7", name: "Geely GC7" },
      {value: "Geely GC9", name: "Geely GC9" },
      {value: "Geely GX2", name: "Geely GX2" },
      {value: "Geely GX7", name: "Geely GX7" },
      {value: "Geely GX9", name: "Geely GX9" },
      {value: "Geely Gleagle", name: "Geely Gleagle" },
      {value: "Geely Haijing", name: "Geely Haijing" },
      {value: "Geely Haoqing", name: "Geely Haoqing" },
      {value: "Geely Jingang", name: "Geely Jingang" },
      {value: "Geely K17", name: "Geely K17" },
      {value: "Geely LC", name: "Geely LC" },
      {value: "Geely LC Cross", name: "Geely LC Cross" },
      {value: "Geely MK", name: "Geely MK" },
      {value: "Geely MK Cross", name: "Geely MK Cross" },
      {value: "Geely Meiri", name: "Geely Meiri" },
      {value: "Geely Panda", name: "Geely Panda" },
      {value: "Geely SC3", name: "Geely SC3" },
      {value: "Geely SC5", name: "Geely SC5" },
      {value: "Geely SC7", name: "Geely SC7" },
      {value: "Geely SL", name: "Geely SL" },
      {value: "Geely SX7", name: "Geely SX7" },
      {value: "Geely TX4", name: "Geely TX4" },
      {value: "Geely Yuanjin", name: "Geely Yuanjin" },
      {value: "Geely Ziyoujian", name: "Geely Ziyoujian" },
      {value: "Chery A13", name: "Chery A13" },
      {value: "Chery A15", name: "Chery A15" },
      {value: "Chery A19", name: "Chery A19" },
      {value: "Chery A3", name: "Chery A3" },
      {value: "Chery A5", name: "Chery A5" },
      {value: "Chery A6", name: "Chery A6" },
      {value: "Chery Arrizo 3", name: "Chery Arrizo 3" },
      {value: "Chery Arrizo 5", name: "Chery Arrizo 5" },
      {value: "Chery Arrizo 7", name: "Chery Arrizo 7" },
      {value: "Chery Cowin", name: "Chery Cowin" },
      {value: "Chery E3", name: "Chery E3" },
      {value: "Chery E5", name: "Chery E5" },
      {value: "Chery Eastar", name: "Chery Eastar" },
      {value: "Chery Elara", name: "Chery Elara" },
      {value: "Chery Envy", name: "Chery Envy" },
      {value: "Chery Face", name: "Chery Face" },
      {value: "Chery Grand Tiggo", name: "Chery Grand Tiggo" },
      {value: "Chery M11", name: "Chery M11" },
      {value: "Chery Tiggo", name: "Chery Tiggo" },
      {value: "Chery Tiggo 3", name: "Chery Tiggo 3" },
      {value: "Chery Tiggo 5", name: "Chery Tiggo 5" },
      {value: "Renault Samsung SM5", name: "Renault Samsung SM5" },
      {value: "MG 350", name: "MG 350" },
      {value: "MG 550", name: "MG 550" },
      {value: "MG MG 3", name: "MG MG 3" },
      {value: "MG MG 5", name: "MG MG 5" },
      {value: "MG MG 6", name: "MG MG 6" },
      {value: "MG MG 7", name: "MG MG 7" },
      {value: "FAW Besturn B50", name: "FAW Besturn B50" },
      {value: "FAW Besturn B70", name: "FAW Besturn B70" },
      {value: "FAW Besturn X80", name: "FAW Besturn X80" },
      {value: "FAW N5", name: "FAW N5" },
      {value: "FAW N7", name: "FAW N7" },
      {value: "FAW V5", name: "FAW V5" },
      {value: "JAC Motors J5", name: "JAC Motors J5" },
      {value: "JAC Motors J6", name: "JAC Motors J6" },
      {value: "JAC Motors S5", name: "JAC Motors S5" },
      {value: "Lifan 620", name: "Lifan 620" },
      {value: "Lifan X50", name: "Lifan X50" },
      {value: "Lifan X60", name: "Lifan X60" },
      {value: "Landwind X6", name: "Landwind X6" },
      {value: "Datsun Go", name: "Datsun Go" },
      {value: "Datsun Go+", name: "Datsun Go+" },
      {value: "Datsun On-Do", name: "Datsun On-Do" },
      {value: "Datsun mi-DO", name: "Datsun mi-DO" },
      {value: "Datsun redi-GO", name: "Datsun redi-GO" },
      {value: "Besturn B30", name: "Besturn B30" },
      {value: "Besturn B50", name: "Besturn B50" },
      {value: "Besturn B70", name: "Besturn B70" },
      {value: "Besturn B90", name: "Besturn B90" },
      {value: "Besturn X80", name: "Besturn X80" },
      {value: "ZNEN Koala", name: "ZNEN Koala" },
      {value: "Ravon Gentra", name: "Ravon Gentra" },
      {value: "Ravon R2", name: "Ravon R2" },
      {value: "Ravon R3", name: "Ravon R3" },
      {value: "Ravon R4", name: "Ravon R4" },
      {value: "DeLorean DMC-12", name: "DeLorean DMC-12" },
      {value: "Volga Siber", name: "Volga Siber" },
      {value: "IKCO Samand LX", name: "IKCO Samand LX" },
      {value: "IKCO Samand SE", name: "IKCO Samand SE" },
      {value: "UAZ Patriot", name: "UAZ Patriot" },
      {value: "ZAZ Chance", name: "ZAZ Chance" },
      {value: "ZAZ Forza", name: "ZAZ Forza" },
      {value: "ZAZ Sens", name: "ZAZ Sens" },
      {value: "ZAZ Vida", name: "ZAZ Vida" } 
  ],
  labelField: 'name',
  searchField: ['name'],
  render: {
      optgroup_header: function(data, escape) {
          return '<div class="optgroup-header">' + escape(data.label) + ' <span class="scientific">' + escape(data.label_scientific) + '</span></div>';
      }
  }
});

/*
//E-mail Ajax Send
$("form.callback").submit(function() { //Change
	var th = $(this);
	$.ajax({
		type: "POST",
		url: "mail.php", //Change
		data: th.serialize()
	}).done(function() {
		$(th).find('.success').addClass('active').css("display", "flex").hide().fadeIn();
		setTimeout(function() {
			$(th).find('.success').removeClass('active').fadeOut();
			th.trigger("reset");
		}, 3000);
	});
	return false;
});
*/



$(window).on('load', function() {
	$('.preloader').delay(1000).fadeOut('slow');
});
